### ISSUE TITLE
jetcard installation error for Jetpack 4.2.2 : nv-l4t-usb-device-mode.sh file not found.

### ISSUE THREAD

**Issue by alankongfq** [NVIDIA-AI-IOT/jetcard#17]
Hi there,

I tried creating the installation for jetcard from scratch by starting from flashing Jetpack 4.2.2 to my sd card and then trying to install jetcard into jetson. However, when running ./install.sh, i encountered the error that nv-l4t-usb-device-mode.sh is not found inside the directory "/opt/nvidia/l4t-usb-device-mode/". Instead I had only nv-l4t-usb-device-mode-config.sh instead. Can anyone help with this?

When I change the ./install.sh to include nv-l4t-usb-device-mode-config.sh, the bash does not execute all the way too.

**Comment by tishafok** [comment]
bump

**Comment by EnzoZafra** [comment]
bump,

**Comment by EnzoZafra** [comment]
@alankongfq, @tishafok just figured this out. Try using the `jetpack_4.2.2` branch!
https://github.com/NVIDIA-AI-IOT/jetcard/tree/jetpack_4.2.2

**Comment by datavici** [comment]
The main install.sh does not appear to have been debugged.  It has adds an extra slash but putting a trailing slash in the $DIR variable.  Remove that and you should be solid.

**Comment by datavici** [comment]
Also, filename is wrong.  anywhere it is <b>nv-l4t-usb-device-mode.sh</b> it should be changed to <b>nv-l4t-usb-device-mode-start.sh</b>

**Comment by jhango21** [comment]
I saw same issue with 
When I change the ./install.sh to include nv-l4t-usb-device-mode-start.sh, the bash does not execute all the way too.

**Comment by alankongfq** [comment]
I had since switch to Jetpack 4.3 and 4.4 for my development. @EnzoZafra solution works by cloning from the branch instead of the master.
As for debugging install.sh, I havent done any deep dive into investigating this and dont wish to mess up what was predefined in the shell scripts.

As such I am closing this issue as the solution provided @EnzoZafra has done what was asked for.
